### ISSUE TITLE
Pypi documentation not creating point right symbol

### ISSUE THREAD

**Issue by P-S-S-M** [fusion-energy/neutronics_material_maker#25]
Your pypi documentation is not creating the point right symbol in the documentation at the link below in edge.

https://pypi.org/project/neutronics-material-maker/?msclkid=2a28ac08c0b811ec9232d524ef7bc822

**Comment by shimwell** [comment]
Thanks for letting me know.

I guess this is because the readme.md is written in markdown and pypi doesn't render markdown

The :point_right: works here on GitHub as GitHub renders the markdown

https://github.com/fusion-energy/neutronics_material_maker

Do let me know if you are aware of a fix for this

**Comment by P-S-S-M** [comment]
Np, not aware of a fix, just thought I would let you know.

**Comment by shimwell** [comment]
Thanks for letting me know, I shall keep this in mind if I notice a solution
